version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic
    ports:
      - 9200:9200
      # - 9300:9300

volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge